### ISSUE TITLE
tslib is listed as a dev dependency 

### ISSUE THREAD

**Issue by eladchen** [zgid123/string-interpolation-js#12]
Seems like "tslib" is listed under the package "devDependencies", but I believe you mean "dependencies".

Long story short, this package dependencies fail to install when using npm ci --omit=dev.

**Comment by zgid123** [comment]
hi @eladchen, can you gimme more info or the error message?

**Comment by zgid123** [comment]
nvm, I already found out that. Thank you for the info

**Comment by zgid123** [comment]
@eladchen I already publish 1.0.6. It may fix your issue. Please let me know if you have any issue. Thanks for your info again

**Comment by eladchen** [comment]
Thanks
